Add remove tasks
Ochiengsteven/to-do pull request #2
Opened 2023-07-12 12:02 UTC by Ochiengsteven

I have completed all the project requirements. Here's a summary of the changes:

- Removed all hardcoded items from the tasks array.
- Created a new JavaScript file, taskManager.js, to handle the new functionality.
- Implemented the addTask function to add new tasks to the array.
- Implemented the removeTask function to delete tasks from the array.
- Implemented the functionality to edit task descriptions.
- New tasks now have the completed property set to false and the index property set to the value of the new array length.
- Deleting a task updates all remaining items' indexes to represent the current list order and ensure uniqueness.

All changes made to the To-Do List are now saved in local storage.
These changes enhance the To-Do List by making it dynamic, allowing users to add, delete, and edit tasks while persistently storing the changes in local storage.

2023-07-12 13:00 UTC, V-Blaze requested changes
## Hi @Ochiengsteven , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![giphy](https://user-images.githubusercontent.com/107632780/229314554-3700de13-2c00-46d5-bc77-46ad09af7467.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Add and remove functionality works ✔
-  Correct GitHub flow👋 
-  Readme looks professional✔

 ## Required Changes ♻️

## Optional suggestions
- [ ] Your commit messages are meaningful, but in your subsequent commit messages, I'll suggest capitalizing the first letter of the sentence as that's the standard practice. :+1: :+1: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 13:00 UTC, V-Blaze commented on src/modules/taskManager.js
> +let tasks = [];
- - You have done great so far, :+1: :+1: But there are some features you still need to implement before moving to the next milestone. :+1: 
> Implement a function for editing task descriptions.
- [ ] As stated in the project requirement, you need to implement the functionality to edit a task. I'll suggest you write out the functionality for that. :+1: :+1:

2023-07-12 13:00 UTC, V-Blaze commented on src/index.js
> +      index: Math.floor(Math.random() * 1000),
> By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).
- [ ] While adding a new task, I can see that you are generating a random ID for the task, But as stated in the project requirement, you are meant to set the id of a new task to equal the current length of the tasks. I'll suggest you update this logic in your code, :smile: :wave: :+1:

2023-07-12 13:00 UTC, V-Blaze commented on src/index.js
> +    localStorage.setItem('tasks', JSON.stringify(getTasks())); // Save updated tasks to local storage
> Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique(i.e. if you're deleting the first task index 1 from the list, the index of the next task(2) should set to 1)..
- [ ] According to the requirement, you are meant to update the ids of the remaining tasks so that they represent the current order of the task list. I'll suggest you implement this too. :+1: :100:

2023-07-12 13:00 UTC, V-Blaze commented on package.json
> +    "build": "webpack"
- [ ] To make your application open easily and automatically in the browser, I'll suggest you install the npm package called `webpack-dev-server` and then add this script `"start": "webpack serve --open"` in the script object in your `package.json ` file. :+1:

2023-07-13 04:51 UTC, amejid approved these changes
Hi @Ochiengsteven, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter checks passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- ADD, EDIT, and DELETE functionalities working well :heavy_check_mark: 
- Indexes updating upon removal :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 07:04 UTC, merged